### ISSUE TITLE
BCAT folder issue with Linux

### ISSUE THREAD

**Issue by pjeanjean** [Manu098vm/Switch-Gift-Data-Manager#1]
Hey,

Thanks for making this tool, it's amazing work.

I just wanted to report that I had some issues with it on Linux (using the latest Linux version): no matter what I tried, the CLI would always return "Not a valid BCAT folder path. Aborted.".
I still managed to run the previous GUI version (running on dotnet 6.0) through Wine, so I can confirm that my BCAT folder was fine and that the issue is with the detection.

I don't have much experience with dotnet, but looking at the source code I think that the backslashes in the detection method are what causes the issue.

**Comment by Manu098vm** [comment]
Thank you for the report. This should be solved in commit https://github.com/Manu098vm/Switch-Gift-Data-Manager/commit/57ff7a00c9e3824bfaf44201b9fc78c201018816. You can try it out once it finishes building on the [GitHub Actions page](https://github.com/Manu098vm/Switch-Gift-Data-Manager/actions/runs/4263861773) :)

**Comment by pjeanjean** [comment]
Thanks for the quick response, I can confirm that everything works fine now.

I'll just add that the way it is built, the executable requires OpenSSL version 3 or more, otherwise it fails during generation with an Internal Error (which is completely fine, I'm just reporting that in case someone else struggles to run it because they have a partially updated system).
