### ISSUE TITLE
Feature Request - MGDB Download

### ISSUE THREAD

**Issue by Ninjistix** [Manu098vm/Switch-Gift-Data-Manager#2]
option or ability to automatically download the latest event pokemon from the Event Gallery from https://github.com/projectpokemon/EventsGallery

**Comment by Manu098vm** [comment]
Please better describe your idea and eventually describe a concrete example of how and why it would be useful. I'm unsure on what you're suggesting exactly.

**Comment by Ninjistix** [comment]
the program is to manage mystery gifts, https://github.com/projectpokemon/EventsGallery contains all of the mystery gifts.

the program should have an option to download the currently available mystery gifts to a directory that the program can then use to organize/inject the mystery gift data.

**Comment by Manu098vm** [comment]
Added MGDB download in https://github.com/Manu098vm/Switch-Gift-Data-Manager/commit/72d95557556b0ddd2ba5516b0e5d909b8eecb845
