### ISSUE TITLE
MGDB downloaded in wrong directory

### ISSUE THREAD

**Issue by Asia81** [Manu098vm/Switch-Gift-Data-Manager#3]
As featured in the thread, the mgdb should be downloaded next to the .exe, but it has been downloaded in my %appdata% folder instead.
C:\Users\Asia81\AppData\Local\Temp\.net\SwitchGiftDataManager.WinForm\LKUsd7ZpBW4AmQAabfXNUu+mPmzcRks=\mgdb

**Comment by Manu098vm** [comment]
Apparently the method to get the assembly directory only works when the exectuable is compiled but not published. I'll see if I can find some workaround.

**Comment by Manu098vm** [comment]
Should be solved in https://github.com/Manu098vm/Switch-Gift-Data-Manager/commit/7e05c2fa8a835df403b39d545ec8d09ba5ce73cb. I'll release an hotfix patch soon.

Edit: Released.
