### ISSUE TITLE
problem with Bcat extraction

### ISSUE THREAD

**Issue by XiNaru** [Manu098vm/Switch-Gift-Data-Manager#4]
hey i want excract bcat from legends arceus. i do what the tutorial say, but it comes always the message: save data is empty

**Comment by Manu098vm** [comment]
Connect the game online and use the Mystery Gift option at least once, no matter if there are no gifts. this is required for the BCAT to be initialized. 
EmuNand/EmuMMC and Emulators are not supported.

**Comment by XiNaru** [comment]
ah i understand 
thanks, then i cannout do this...crap.....my cfw switch unfortunally is banned...
